# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go

on:
  push:
    branches: [ "master" ]
    paths: 
      - '**.go'
  pull_request:
    branches: [ "master" ]
    paths: 
      - '**.go'
  workflow_dispatch:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21

    - name: Build the project
      run: go build -v ./...

    - name: Vet the Code
      run: go vet ./...

    - name: Run Tests Test
      run: go test -v ./...
